name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      use-emoji:
       type: boolean
       description: Include 🎉🤣 emojis ex x.x.x
       required: true
      environment:
        type: environment
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      route: ${{ env.ROUTE }}
      test: ${{ env.TEST }}
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
          if [ ${{ github.event.inputs.use-emoji }} == true ]
          then
            echo 'Success. Using emojis 🎉🤣.'
            exit 0
            echo 'This line should not be executed'
          else
            echo 'No emojis'
            exit 1
          fi
