name: Test Condition
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run action in. 
        type: choice
        required: true
        default: dev-cc
        options:
        - dev-use
        - dev-usw
        - dev-cc
        - test-cc

jobs:
  test_condition:
    runs-on: ubuntu-latest
    env:
      cluster_env_suffix: ${{ inputs.environment == "dev-cc" && "dev" || inputs.environment }}
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Substitute name
        run: |
           echo echo -e "\e[32m[INFO] Cluster prefix is: ${{ env.cluster_env_suffix }} "
           
