name: Test YQ
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'What is your name'
        required: false
        default: 'Jerome'

jobs:
  test_yq:
    runs-on: ubuntu-latest
    env:
      WORKINGDIRECTORY: 'demofiles'
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKINGDIRECTORY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Install YQ Tools
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/4.34.1/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
      - name: Substitute name
        env:
          NEW_NAME: ${{ github.event.inputs.name }}
        run: |
           yq  '.employee.name = strenv(NEW_NAME)' -i employee.yaml
           cat employee.yaml
