name: 'Test Workflow Execution'
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What Cluster to deploy
        options: 
        - prod
        - non-prod
        - all-clusters
        required: true
        default: all-clusters
      
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: 
         if  [[ ${{ github.event.inputs.name }} == 'prod' ]];
         then
           echo '::set-output name=run_matrix::[{"gh_environment":"prod" }]'
         elif [[ ${{ github.event.inputs.name }} == 'non-prod' ]];
         then
           echo '::set-output name=run_matrix::[{"gh_environment":"non-prod" }]'
         else
           echo '::set-output name=run_matrix::[{"gh_environment":"prod" },{"gh_environment":"non-prod"}]'
         fi  
    outputs:
      run_matrix: ${{ steps.set-matrix.outputs.run_matrix }}

  run-matrix:
    needs: build-matrix
    runs-on: ubuntu-latest
    environment: ${{ matrix.gh_environment }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.build-matrix.outputs.run_matrix) }}
    steps:
      - run: |
          echo "Hello from ${{ secrets.MY_ENVIRONMENT }}!"
          
